<Project>

	<PropertyGroup>
		<Deterministic>true</Deterministic>
		<GenerateDocumentationFile>false</GenerateDocumentationFile>
		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>latest</LangVersion>
		<NeutralLanguage>en</NeutralLanguage>
		<Nullable>enable</Nullable>
		<TargetFramework>net10.0</TargetFramework>
	</PropertyGroup>

</Project>
