<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
		<UserSecretsId>e002b3dc-3c33-4c09-93a2-a67a2d8e207b</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.Data.SqlClient.Extensions.Azure" Version="7.0.2" />
		<PackageReference Include="Microsoft.Identity.Web" Version="4.1.0" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Textbase.Application\Textbase.Application.csproj" />
		<ProjectReference Include="..\Textbase.Infrastructure\Textbase.Infrastructure.csproj" />
	</ItemGroup>

</Project>
